ACS.Admin/Controllers/SimulateController.cs
using ACS.Admin.Auth;
using ACS.Admin.Models;
using ACS.Shared.Models;
using ACS.Shared.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace ACS.Admin.Controllers
{
    [Authorize(Roles = UserRole.Administrator + "," + UserRole.Editor + "," + UserRole.ReadonlyUser)]
    public class SimulateController : Controller
    {
        private readonly ICacheService _cacheService;
        private readonly ITargetMatchingService _targetMatchingService;

        public SimulateController(ICacheService cacheService, ITargetMatchingService targetMatchingService)
        {
            _cacheService = cacheService;
            _targetMatchingService = targetMatchingService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search([ModelBinder(typeof(ConfigQueryRequestParamsModelBinder))] ConfigQueryRequestParams requestParams)
        {
            List<CompiledCacheEntry>? cacheEntries = await _cacheService.GetAsync(requestParams.AgentName);

            Log
                .ForContext("RequestParams", requestParams)
                .Information("Performed target simulation");

            return View(_targetMatchingService.GetMatchingFragments(cacheEntries, requestParams));
        }

        public IActionResult NoFragments()
        {
            return View();
        }
    }
}

ACS.Admin/Views/Shared/_DataTableItemList.cshtml
<script src="~/lib/datatables/datatables.min.js" asp-append-version="true"></script>
<script type="text/javascript">
    new DataTable('#dataTable', {
        pageLength: 25,
        autoWidth: false,
        order: [
            [1, 'asc']
        ],
        stateSave: true,
        responsive: true
    });
</script>

ACS.Admin/Views/Shared/_DataTableLinkedItemList.cshtml
<script src="~/lib/datatables/datatables.min.js" asp-append-version="true"></script>
<script type="text/javascript">
    let table = new DataTable('#dataTable', {
        select: {
            style: 'shift-multi',   // or 'os' / 'single'
            selector: 'td:first-child input[type="checkbox"]',
        },
        columnDefs: [
            {
                orderable: false,
                targets: 0
            }
        ],
        order: [[2, 'asc']],
        paging: false
    });

    // Select all checked rows on initial load
    table.rows().every(function () {
        const row = $(this.node());
        const checkbox = row.find('input[type="checkbox"]');
        if (checkbox.prop('checked')) {
            this.select();
        }
    });
</script>

ACS.Admin/Views/Shared/_DataTableScriptsPartial.cshtml
<script src="~/lib/datatables/datatables.min.js" asp-append-version="true"></script>
<script type="text/javascript">
    new DataTable('#dataTable', {
        
        pageLength: 25,
        autoWidth: false,
        order: [
            [1, 'asc']
        ],
        stateSave: true,
        responsive: true
    });
</script>

ACS.Admin/Views/Shared/_FragmentSelectionList.cshtml
@using ACS.Shared.Models
@{
    IEnumerable<FragmentSelection> fragmentSelections = ViewBag.FragmentSelections;
}

<h3>Linked configuration fragments</h3>
<table class="table" id="dataTable">
    <thead>
        <tr>
            <th class="col-sm-1">Linked</th>
            <th class="col-sm-1">Id</th>
            <th class="col-sm-3">Name</th>
            <th class="col-sm-1">Priority</th>
            <th class="col-sm-5">Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @fragmentSelections)
        {
            <tr>
                <td>
                    <input class="form-check-input" asp-for="@item.Linked" id="fragment-@item.Fragment.Id" value="@item.Fragment.Id" name="linkedFragmentIds" />
                </td>
                <td>
                    <a asp-controller="Fragments" asp-action="Edit" asp-route-id="@item.Fragment.Id" target="_blank">@item.Fragment.Id</a>
                </td>
                <td class="col">@item.Fragment.Name</td>
                <td class="col">@item.Fragment.Priority</td>
                <td class="col">@item.Fragment.Description</td>
            </tr>
        }
    </tbody>
</table>

ACS.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACS Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/datatables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ACS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Agent Configuration Server</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Fragments" asp-action="Index">Configuration Fragments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Targets" asp-action="Index">Targets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Simulate" asp-action="Index">Simulate</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity?.IsAuthenticated == true)
                {
                <div class="account">
                    <div class="name text-light">
                        <span>Signed in as: </span>
                        <span style="font-weight: 500">@GetLoggedInUserId()</span>
                    </div>
                    <div class="signout">
                        <a asp-controller="Account" asp-action="LogOut" class="btn btn-primary">Sign Out</a>
                    </div>
                </div>
                }
            </div>
        </nav>
    </header>
    <div class="container-fluid gx-5">
        <main role="main" class="pb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container"></div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@{
    string? GetLoggedInUserId()
    {
        return User.FindFirst("preferred_username")?.Value;
    }
}

ACS.Admin/Views/Shared/_TargetSelectionList.cshtml
@using ACS.Shared.Models
@{
    IEnumerable<TargetSelection> targetSelections = ViewBag.TargetSelections;
}

<h3>Linked targets</h3>
<table class="table" id="dataTable">
    <thead>
        <tr>
            <th class="col-sm-1">Linked</th>
            <th class="col-sm-1">Id</th>
            <th class="col-sm-2">Agent Name</th>
            <th class="col-sm-5">Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @targetSelections)
        {
            <tr>
                <td>
                    <input class="form-check-input" asp-for="@item.Linked" value="@item.Target.Id" name="linkedTargetIds" />
                </td>
                <td>
                    <a asp-controller="Targets" asp-action="Edit" asp-route-id="@item.Target.Id" target="_blank">@item.Target.Id</a>
                </td>
                <td class="col">@item.Target.AgentName</td>
                <td class="col">@item.Target.Description</td>
            </tr>
        }
    </tbody>
</table>

ACS.Admin/Views/Shared/_TextEditorScriptsPartial.cshtml
@using ACS.Admin.Auth
@{
    bool isAdmin = User.IsInRole(UserRole.Administrator);
    bool isEditor = User.IsInRole(UserRole.Editor);
    bool inputDisabled = !(isAdmin || isEditor);
}

<script src="~/lib/ace-js/ace.js" asp-append-version="true"></script>
<script type="text/javascript">
    var editor = ace.edit("editor", {
        theme: 'ace/theme/tomorrow_night',
        mode: 'ace/mode/xml',
        minLines: 10,
        maxLines: 25
    });

    var textArea = document.getElementById('editorInput');
    editor.getSession().setValue(textArea.value);

    editor.getSession().on('change', function () {
        textArea.value = editor.getSession().getValue();
    });

    editor.setReadOnly(@(inputDisabled ? "true" : "false"));
</script>

ACS.Admin/Views/Shared/_TooltipScriptsPartial.cshtml
<script type="text/javascript">
    $(function () {
        $('.help-text,input').tooltip({
            placement: 'right'
        });
    })
</script>